# Generated by Django 5.0.6 on 2024-07-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.IntegerField(primary_key=True, serialize=False)),
                ("course", models.IntegerField(null=True)),
                ("lesson_name", models.CharField(max_length=200, null=True)),
                ("lesson_num", models.IntegerField(null=True)),
                ("description", models.TextField(null=True)),
                ("topics", models.TextField(null=True)),
                ("activites", models.TextField(null=True)),
                ("last_updated", models.DateTimeField(auto_now_add=True)),
                ("lesson_content", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=200, null=True)),
                ("firstName", models.CharField(max_length=200, null=True)),
                ("lastName", models.CharField(max_length=200, null=True)),
                ("courseEnrolled", models.CharField(max_length=200, null=True)),
                ("cid", models.IntegerField(db_column="cid", null=True)),
                ("valid", models.BooleanField(default=0)),
            ],
        ),
    ]
