# Generated by Django 5.0.6 on 2024-07-15 01:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("idx_EduWeb", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
