# Generated by Django 5.0.6 on 2024-07-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idx_EduWeb", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=200, null=True)),
                ("firstName", models.CharField(max_length=200, null=True)),
                ("lastName", models.CharField(max_length=200, null=True)),
                ("courseEnrolled", models.CharField(max_length=200, null=True)),
                ("cid", models.IntegerField(db_column="cid", null=True)),
                ("valid", models.BooleanField(default=0)),
            ],
        ),
    ]
