# Generated by Django 5.0.6 on 2024-07-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idx_EduWeb", "0004_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="lesson_num",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
